#
# Waking up
#
- id: open_kitchen_blinds_in_the_morning_weekdays
  alias: Open blinds at 6 on weekdays
  trigger:
    platform: time
    at: 06:00:00
  condition:
    - condition: sun
      after: sunrise
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
    - condition: template
      value_template: "{{ is_state('group.users', 'home') }}"
  action:
  - service: cover.set_cover_position
    data:
      entity_id: cover.level
      position: 50
- id: open_kitchen_blinds_in_the_morning_weekend
  alias: Open blinds at 7:30 on weekends
  trigger:
    platform: time
    at: 07:30:00
  condition:
    - condition: sun
      after: sunrise
    - condition: time
      weekday:
        - sat
        - sun
    - condition: template
      value_template: "{{ is_state('group.users', 'home') }}"
  action:
  - service: cover.open_cover
    data:
      entity_id: cover.level
- id: open_kitchen_blinds_on_sunrise_weekdays
  alias: Open blinds on sunrise on weekdays
  trigger:
    platform: sun
    event: sunrise
  condition:
    - condition: time
      after: 05:55:00
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
    - condition: template
      value_template: "{{ is_state('group.users', 'home') }}"
  action:
  - service: cover.set_cover_position
    data:
      entity_id: cover.level
      position: 50
- id: open_kitchen_blinds_on_sunrise_weekdays
  alias: Open blinds on sunrise on weekdays
  trigger:
    platform: sun
    event: sunrise
  condition:
    - condition: time
      after: 07:25:00
      weekday:
        - sat
        - sun
    - condition: template
      value_template: "{{ is_state('group.users', 'home') }}"
  action:
  - service: cover.open_cover
    data:
      entity_id: cover.level

#
# Leaving for work and school
#
- id: close_blinds_after_leaving_home
  alias: Close blinds whene everyon leaves for work/school
  trigger:
    platform: state
    entity_id: group.users
    to: not_home
    for:
      minutes: 20
  action:
  - service: cover.close_cover
    data:
      entity_id: cover.level

#
# Ready for night
#
- id: close_kitchen_blinds_at_sunset
  trigger:
    platform: sun
    event: sunset
    offset: '+01:00:00'
  action:
  - service: cover.close_cover
    data:
      entity_id: cover.level
  


#
# GARDEN sprinklers and lights
#
- id: turn_on_sprinkler1
  alias: Turn on 1st sprinkler
  initial_state: 'off'
  trigger:
    platform: time
    at: 01:00:00
  action:
    service: homeassistant.turn_on
    entity_id: switch.sprinkler_1_1
- id: turn_off_sprinkler1
  alias: Turn off 1st sprinkler after 5 minutes
  initial_state: 'off'
  trigger:
    platform: state
    entity_id: switch.sprinkler_1_1
    from: 'off'
    to: 'on'
    for:
      minutes: 5
  action:
    service: homeassistant.turn_off
    entity_id: switch.sprinkler_1_1

- id: light_up_terrace_when_dark
  alias: Lit terrace up when dark
  trigger:
  - platform: sun
    event: sunset
    offset: '+01:00:00'
  condition:
    condition: template
    value_template: "{{ not is_state('group.users', 'home') }}"
  action:
  - service: script.turn_on_terrace_lights
- id: turn_off_garden_lights_in_late_evening
  alias: Turn off garden lights late evening
  trigger:
    platform: sun
    event: sunset
    offset: '+04:00:00'
  action:
  - service: script.turn_off_terrace_lights

#
# Alarm
#
- id: alarm_armed_away
  alias: '[Alarm] Away Mode Armed'
  trigger:
  - platform: state
    entity_id: alarm_control_panel.house
    to: armed_away
  action:
  - data:
      message: The house alarm has been switched on in away mode. Goodbye
    service: notify.discord_notify
- id: alarm_armed_home
  alias: '[Alarm] Home Mode Armed'
  trigger:
  - platform: state
    entity_id: alarm_control_panel.house
    to: armed_home
  action:
  - data:
      message: The house alarm has been switched on in home mode. Goodnight
    service: notify.discord_notify
- id: alarm_arming_away
  alias: '[Alarm] Away Mode Arming'
  trigger:
  - platform: state
    entity_id: alarm_control_panel.house
    to: pending
  action:
  - data:
      message: House alarm activating, ensure all doors and windows are closed
    service: notify.discord_notify
- id: alarm_disarmed
  alias: '[Alarm] Disarmed'
  trigger:
  - platform: state
    entity_id: alarm_control_panel.house
    to: disarmed
  action:
  - data:
      message: The house alarm has been Deactivated
    service: notify.discord_notify
- id: alarm_triggered
  alias: '[Alarm] Triggered'
  trigger:
  - platform: state
    entity_id: alarm_control_panel.house
    to: triggered
  action:
  - service: notify.discord_alert
    data:
      message: ALARM TRIGGERED!!! {{ states[states.alarm_control_panel.house.attributes.changed_by.split(".")[0]][
        states.alarm_control_panel.house.attributes.changed_by.split(".")[1]].name
        }}
- id: alarm_warning
  alias: '[Alarm] Warning'
  trigger:
  - platform: state
    entity_id: alarm_control_panel.house
    to: warning
  action:
  - service: notify.discord_alert
    data:
      message: ALARM Warning {{ states[states.alarm_control_panel.house.attributes.changed_by.split(".")[0]][
        states.alarm_control_panel.house.attributes.changed_by.split(".")[1]].name
        }}
- id: arm_alarm_when_all_users_left_home
  alias: '[Alarm] Auto arm'
  condition:
    condition: state
    entity_id: alarm_control_panel.house
    state: disarmed
  trigger:
    platform: state
    entity_id: group.users
    to: not_home
    for:
      minutes: 21
  action:
  - service: alarm_control_panel.alarm_arm_away
- id: disarm_alarm_when_user_comes_home
  alias: '[Alarm] Auto disarm'
  condition:
    condition: state
    entity_id: alarm_control_panel.house
    state: armed_away
  trigger:
    platform: state
    entity_id: group.users
    to: home
  action:
  - service: alarm_control_panel.alarm_disarm
    data:
      entity_id: alarm_control_panel.house
      code: 5464
- id: blink_garden1_light_when_alarm_triggered
  alias: Blink Garden Terrace Light When Alarm Triggered
  condition:
    condition: state
    entity_id: alarm_control_panel.house
    state: triggered
  trigger:
    platform: time
    seconds: /2
  action:
  - service: switch.toggle
    data:
      entity_id: switch.gateway_0_7
  - service: switch.toggle
    data:
      entity_id: switch.gateway_0_8
- id: cleanup_after_triggered_alarm_timeouts
  alias: Garden lights on after triggered alarm timeouts
  trigger:
  - platform: state
    entity_id: alarm_control_panel.house
    from: triggered
    to: armed_away
  action:
  - service: script.turn_on_terrace_lights
- id: cleanup_after_triggered_alarm_deactivated
  alias: Cleanup after alarm deactivated
  trigger:
  - platform: state
    entity_id: alarm_control_panel.house
    from: triggered
    to: disarmed
  action:
  - service: script.turn_off_terrace_lights

#
# Warnings, notifications
#
- id: alert_when_cold_and_window_open_for_too_long
  alias: Alert when window open for long time
  condition:
    condition: numeric_state
    entity_id: sensor.yr_temperature
    below: 10
  trigger:
    platform: state
    entity_id:
    - binary_sensor.living_room_sensor_node_2_2
    - binary_sensor.living_room_sensor_node_2_3
    - binary_sensor.living_room_sensor_node_2_4
    - binary_sensor.bedroom_2_sensor_node_3_2
    - binary_sensor.bedroom_sensor_node_4_2
    to: 'on'
    for:
      minutes: 20
  action:
  - service: notify.discord_alert
    data_template:
      message: '{{ trigger.to_state.attributes.friendly_name }} is opened too long'

