- id: turn_on_sprinkler1
  alias: Turn on 1st sprinkler
  trigger:
    platform: time
    at: '01:00:00'
  action:
    service: homeassistant.turn_on
    entity_id: switch.sprinkler_1_1
- id: turn_off_sprinkler1
  alias: Turn off 1st sprinkler after 5 minutes
  trigger:
    platform: state
    entity_id: switch.sprinkler_1_1
    from: 'off'
    to: 'on'
    for:
      minutes: 5
  action:
    service: homeassistant.turn_off
    entity_id: switch.sprinkler_1_1


- id: alarm_armed_away
  alias: '[Alarm] Away Mode Armed'
  trigger:
  - platform: state
    entity_id: alarm_control_panel.house
    to: 'armed_away'
  action:
  - data:
      message: 'The house alarm has been switched on in away mode. Goodbye'
    service: notify.discord_notify

- id: alarm_armed_home
  alias: '[Alarm] Home Mode Armed'
  trigger:
  - platform: state
    entity_id: alarm_control_panel.house
    to: 'armed_home'
  action:
  - data:
      message: 'The house alarm has been switched on in home mode. Goodnight'
    service: notify.discord_notify

- id: alarm_arming_away
  alias: '[Alarm] Away Mode Arming'
  trigger:
  - platform: state
    entity_id: alarm_control_panel.house
    to: 'pending'
  action:
  - data:
      message: 'House alarm activating, ensure all doors and windows are closed'
    service: notify.discord_notify

- id: alarm_disarmed
  alias: '[Alarm] Disarmed'
  trigger:
  - platform: state
    entity_id: alarm_control_panel.house
    to: 'disarmed'
  action:
#  - service: switch.turn_off
#    entity_id: switch.siren_switch
  - data:
      message: 'The house alarm has been Deactivated'
    service: notify.discord_notify

- id: alarm_triggered
  alias: '[Alarm] Triggered'
  trigger:
  - platform: state
    entity_id: alarm_control_panel.house
    to: 'triggered'
  action:
#  - service: switch.turn_on
#    entity_id: switch.siren_switch
  - service: notify.discord_alert
    data:
      message: 'ALARM TRIGGERED!!! {{ states[states.alarm_control_panel.house.attributes.changed_by.split(".")[0]][ states.alarm_control_panel.house.attributes.changed_by.split(".")[1]].name }}'

- id: alarm_warning
  alias: '[Alarm] Warning'
  trigger:
  - platform: state
    entity_id: alarm_control_panel.house
    to: 'warning'
  action:
  - service: notify.discord_alert
    data:
      message: 'ALARM Warning {{ states[states.alarm_control_panel.house.attributes.changed_by.split(".")[0]][ states.alarm_control_panel.house.attributes.changed_by.split(".")[1]].name }}'

- id: arm_alarm_when_all_users_left_home
  alias: '[Alarm] Auto arm'
  condition: 
    condition: state
    entity_id: alarm_control_panel.house
    state: 'disarmed'
  trigger:
    platform: state
    entity_id: group.users
    to: 'not_home'
    for: 
      minutes: 15
  action:
    - service: alarm_control_panel.alarm_arm_away

- id: disarm_alarm_when_user_comes_home
  alias: '[Alarm] Auto disarm'
  condition:
    condition: state
    entity_id: alarm_control_panel.house
    state: 'disarmed'
  trigger:
    platform: state
    entity_id: group.users
    from: 'not_home'
    to: 'home'
  action:
    - service: alarm_control_panel.alarm_disarm
