homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Warsaw

  customize: !include customize.yaml

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret http_password
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123
  server_port: 8080
# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
  ip_ban_enabled: True
  login_attempts_threshold: 100
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Weather Prediction
sensor:
  - platform: yr
    monitored_conditions:
      - temperature
      - symbol
      - humidity
      - windSpeed
      - cloudiness
  - platform: time_date
    display_options:
      - 'date_time'
  - platform: template
    sensors:
      bedroom_2_controller_dead:
        value_template: >
          {% if states.binary_sensor.bedroom_2_sensor_node_3_99.last_updated %}
          {{as_timestamp(now()) - as_timestamp(states.binary_sensor.bedroom_2_sensor_node_3_99.last_updated) > 3600}}
          {% else %}
          {{false}}
          {% endif %}
        friendly_name: 'Kids bedroom controller not reporting for 1 hour'
        entity_id:
          - sensor.date__time
      bedroom_controller_dead:
        value_template: >
          {% if states.binary_sensor.bedroom_sensor_node_4_99.last_updated %}
          {{as_timestamp(now()) - as_timestamp(states.binary_sensor.bedroom_sensor_node_4_99.last_updated) > 3600}}
          {% else %}
          {{false}}
          {% endif %}
        friendly_name: 'Bedroom controller not reporting for 1 hour'
        entity_id: 
          - sensor.date__time     
      living_room_controller_dead:
        friendly_name: 'Living room controller not reporting for 1 hour'
        value_template: >
          {% if states.binary_sensor.living_room_sensor_node_2_99.last_updated %}
          {{as_timestamp(now()) - as_timestamp(states.binary_sensor.living_room_sensor_node_2_99.last_updated) > 3600}}
          {% else %}
          {{false}}
          {% endif %}
        entity_id:
          - sensor.date__time

# Text to speech
tts:
  platform: google

group: !include groups.yaml
automation: !include automations.yaml
alert: !include alerts.yaml
alarm_control_panel: !include alarm.yaml
panel_custom: !include panel_custom.yaml
zone: !include zones.yaml
mysensors:
  gateways:
    - device: '/dev/arduino'
  version: 2.0  

device_tracker:
  - platform: google_maps
    username: !secret google_user
    password: !secret google_password
    new_device_defaults:
      track_new_devices: False
      hide_if_away: False

mqtt:
  broker: 127.0.0.1
  port: 8125
  keepalive: 60
  client_id: home-assistant
  username: homeassistant
  password: !secret mqtt_password

notify:
  - name: push
    platform: html5
    gcm_api_key: !secret firebase_server_key
    gcm_sender_id: !secret firebase_sender_id
  - name: ha_discord
    platform: discord
    token: !secret discord_token
  - name: discord_alert
    platform: group
    services:
      - service: ha_discord
        data:
          target:
            - !secret discord_alerts_channel_id
  - name: discord_notify
    platform: group
    services:
      - service: ha_discord
        data:
          target:
            - !secret discord_notifications_channel_id

logger:
  default: warn
  logs:
    custom_components.alarm_control_panel.bwalarm: info

switch:
  - platform: broadlink
    host: 192.168.0.110
    mac: 'b4:43:0d:f9:1a:32'
    friendly_name: 'Broadlink IR controller'
    type: rm_mini
    
script: !include scripts.yaml

light:
  - platform: yeelight
    devices:
      192.168.1.111:
        name: Living Room
        transition: 1000
#        use_music_mode: True #(defaults to False)
#        save_on_change: False #(defaults to True)

climate:
  - platform: eq3btsmart
    devices:
      living_room1:
        mac: '00:1A:22:09:EB:DF'
xiaomi_aqara:
  gateways:
    - key: !secret xiaomi_gateway_key
zwave:
  usb_path: /dev/zwave

google_assistant:
  project_id: home-assistant-201418
  client_id: !secret google_assistant_client_id
  access_token: !secret google_assistant_access_token
  api_key: !secret google_assistant_api_key
  expose_by_default: false
  entity_config:
    cover.level:
      name: Kitchen blinds
      expose: true
      room: Kitchen
    switch.switch_2:
      name: Sofa lamp
      expose: true
      room: Living room
      aliases:
        - sofa light
    light.gateway_light_7811dc6c9735:
      name: Gateway light
      expose: true
      room: Living room
      aliases:
        - xiaomi light
